# Generated by Django 4.2.6 on 2023-11-30 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mathtutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(blank=True)),
                ('aboutyou', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('doc', models.FileField(blank=True, upload_to='images/')),
                ('dis', models.BooleanField(default=True)),
                ('distance', models.FloatField(default=0.0)),
                ('lati', models.FloatField(default=0.0)),
                ('longi', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('matutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingbyuser', models.FloatField(default=0.0)),
                ('matutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.mathtutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mathtutor',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.sub'),
        ),
    ]
