# Generated by Django 4.2.6 on 2023-11-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtutor',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
